# Generated by Django 5.2.6 on 2025-11-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_student_id_student_id_student_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprequest',
            name='session_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
